# Generated by Django 3.2.5 on 2021-09-25 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='alltimeoffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2021, 11, 24)),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 25), null=True),
        ),
        migrations.AlterField(
            model_name='discountoffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2021, 11, 24)),
        ),
        migrations.AlterField(
            model_name='otheroffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2021, 11, 24)),
        ),
        migrations.AlterField(
            model_name='seasonaloffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2021, 11, 24)),
        ),
    ]
