# Generated by Django 4.2.5 on 2023-10-05 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_auto_20210925_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltimeoffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 5), null=True),
        ),
        migrations.AlterField(
            model_name='discountoffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
        migrations.AlterField(
            model_name='otheroffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
        migrations.AlterField(
            model_name='seasonaloffers',
            name='offerexp',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
    ]
